/* This file was completely auto-generated by the Visual Studio IDE */

using System;
using System.Windows.Forms;

namespace MotorwaySimulator
{
    static class Program
    {
        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {
            Application.EnableVisualStyles();
            Application.SetCompatibleTextRenderingDefault(false);
            Application.Run(new MotorwaySimulatorForm());
        }
    }
}
